### ISSUE TITLE
Thank you ❤️ 

### ISSUE THREAD

**Issue by NielsPilgaard** [Jisu-Woniu/giscus-blazor#3]
Hi there 👋 

I just wanted to let you know that this nuget has solved a giant headache for me, adding Giscus to Blazor Server has been rough, until I was made aware of this nuget 😅 
Thank you!

**Comment by Jisu-Woniu** [comment]
Glad to hear that.

I'm currently studying in university, preparing for postgraduate entrance exam, so I may not be able to update the code frequently.

**Comment by NielsPilgaard** [comment]
Fair enough 👍 I'll gladly help out if needed.
